# Copyright 2017-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.0

EAPI=7

CRATES="
adler32-1.1.0
aho-corasick-0.7.13
ansi_colours-1.0.1
ansi_term-0.11.0
ansi_term-0.12.1
arrayref-0.3.6
arrayvec-0.5.1
atty-0.2.14
autocfg-1.0.0
base64-0.11.0
base64-0.12.2
bat-0.15.4
bincode-1.2.1
bit-set-0.5.2
bit-vec-0.6.2
bitflags-1.2.1
blake2b_simd-0.5.10
bstr-0.2.13
byteorder-1.3.4
cargo-expand-0.6.2
cc-1.0.54
cfg-if-0.1.10
chrono-0.4.11
clap-2.33.1
console-0.11.3
constant_time_eq-0.1.5
content_inspector-0.2.4
crc32fast-1.2.0
crossbeam-utils-0.7.2
dirs-1.0.5
dtoa-0.4.6
encode_unicode-0.3.6
encoding-0.2.33
encoding-index-japanese-1.20141219.5
encoding-index-korean-1.20141219.5
encoding-index-simpchinese-1.20141219.5
encoding-index-singlebyte-1.20141219.5
encoding-index-tradchinese-1.20141219.5
encoding_index_tests-0.1.4
error-chain-0.12.2
fancy-regex-0.3.5
flate2-1.0.14
fnv-1.0.7
getrandom-0.1.14
globset-0.4.5
heck-0.3.1
hermit-abi-0.1.14
indexmap-1.4.0
itoa-0.4.6
lazy_static-1.4.0
lazycell-1.2.1
libc-0.2.71
line-wrap-0.1.1
linked-hash-map-0.5.3
log-0.4.8
memchr-2.3.3
miniz_oxide-0.3.7
num-integer-0.1.43
num-traits-0.2.12
path_abs-0.5.0
plist-1.0.0
ppv-lite86-0.2.8
proc-macro-error-1.0.2
proc-macro-error-attr-1.0.2
proc-macro2-1.0.18
quote-1.0.7
rand-0.7.3
rand_chacha-0.2.2
rand_core-0.5.1
rand_hc-0.2.0
redox_syscall-0.1.56
redox_users-0.3.4
regex-1.3.9
regex-syntax-0.6.18
remove_dir_all-0.5.3
rust-argon2-0.7.0
ryu-1.0.5
safemem-0.3.3
same-file-1.0.6
semver-0.9.0
semver-parser-0.7.0
serde-1.0.114
serde_derive-1.0.114
serde_json-1.0.55
serde_yaml-0.8.13
std_prelude-0.2.12
strsim-0.8.0
structopt-0.3.15
structopt-derive-0.4.8
syn-1.0.33
syn-mid-0.5.0
syn-select-0.2.0
syntect-4.2.0
tempfile-3.1.0
termcolor-1.1.0
terminal_size-0.1.12
termios-0.3.2
textwrap-0.11.0
thread_local-1.0.1
toml-0.5.6
toolchain_find-0.1.4
unicode-segmentation-1.6.0
unicode-width-0.1.7
unicode-xid-0.2.0
vec_map-0.8.2
version_check-0.9.2
walkdir-2.3.1
wasi-0.9.0+wasi-snapshot-preview1
winapi-0.3.8
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.5
winapi-x86_64-pc-windows-gnu-0.4.0
xml-rs-0.8.3
yaml-rust-0.4.4
"

inherit cargo

DESCRIPTION="Wrapper around rustc --pretty=expanded. Shows the result of macro expansion and #[derive] expansion."
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/dtolnay/cargo-expand"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 Apache-2.0 WITH LLVM-exception BSD-2-Clause BSL-1.0 CC0-1.0 LGPL-3.0-or-later MIT Unlicense Zlib"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""
